"""Supported club and men's national teams.

The canonical entries are taken from ESPN's league team feeds for the 2026
season. Keys are normalized lower-case names; aliases are included where a
club is commonly known by a different name.
"""

TEAMS = {
    # English Premier League (eng.1)
    "afc bournemouth": ("AFC Bournemouth", "349"),
    "arsenal": ("Arsenal", "359"),
    "aston villa": ("Aston Villa", "362"),
    "brentford": ("Brentford", "337"),
    "brighton & hove albion": ("Brighton & Hove Albion", "331"),
    "chelsea": ("Chelsea", "363"),
    "coventry city": ("Coventry City", "388"),
    "crystal palace": ("Crystal Palace", "384"),
    "everton": ("Everton", "368"),
    "fulham": ("Fulham", "370"),
    "hull city": ("Hull City", "306"),
    "ipswich town": ("Ipswich Town", "373"),
    "leeds united": ("Leeds United", "357"),
    "liverpool": ("Liverpool", "364"),
    "manchester city": ("Manchester City", "382"),
    "manchester united": ("Manchester United", "360"),
    "newcastle united": ("Newcastle United", "361"),
    "nottingham forest": ("Nottingham Forest", "393"),
    "sunderland": ("Sunderland", "366"),
    "tottenham hotspur": ("Tottenham Hotspur", "367"),
    # La Liga (esp.1)
    "alaves": ("Alavés", "96"),
    "athletic club": ("Athletic Club", "93"),
    "atletico madrid": ("Atlético Madrid", "1068"),
    "barcelona": ("Barcelona", "83"),
    "celta vigo": ("Celta Vigo", "85"),
    "deportivo": ("Deportivo", "90"),
    "elche": ("Elche", "3751"),
    "espanyol": ("Espanyol", "88"),
    "getafe": ("Getafe", "2922"),
    "levante": ("Levante", "1538"),
    "malaga": ("Málaga", "99"),
    "osasuna": ("Osasuna", "97"),
    "racing santander": ("Racing Santander", "87"),
    "rayo vallecano": ("Rayo Vallecano", "101"),
    "real betis": ("Real Betis", "244"),
    "real madrid": ("Real Madrid", "86"),
    "real sociedad": ("Real Sociedad", "89"),
    "sevilla": ("Sevilla", "243"),
    "valencia": ("Valencia", "94"),
    "villarreal": ("Villarreal", "102"),
    # Bundesliga (ger.1)
    "1 fc union berlin": ("1. FC Union Berlin", "598"),
    "bayer leverkusen": ("Bayer Leverkusen", "131"),
    "bayern munich": ("Bayern Munich", "132"),
    "borussia dortmund": ("Borussia Dortmund", "124"),
    "borussia monchengladbach": ("Borussia Mönchengladbach", "268"),
    "eintracht frankfurt": ("Eintracht Frankfurt", "125"),
    "fc augsburg": ("FC Augsburg", "3841"),
    "fc cologne": ("FC Cologne", "122"),
    "hamburg sv": ("Hamburg SV", "127"),
    "mainz": ("Mainz", "2950"),
    "rb leipzig": ("RB Leipzig", "11420"),
    "sc freiburg": ("SC Freiburg", "126"),
    "sc paderborn 07": ("SC Paderborn 07", "3307"),
    "sv elversberg": ("SV Elversberg", "10388"),
    "schalke 04": ("Schalke 04", "133"),
    "tsg hoffenheim": ("TSG Hoffenheim", "7911"),
    "vfb stuttgart": ("VfB Stuttgart", "134"),
    "werder bremen": ("Werder Bremen", "137"),
    # Serie A (ita.1)
    "ac milan": ("AC Milan", "103"),
    "as roma": ("AS Roma", "104"),
    "atalanta": ("Atalanta", "105"),
    "bologna": ("Bologna", "107"),
    "cagliari": ("Cagliari", "2925"),
    "como": ("Como", "2572"),
    "fiorentina": ("Fiorentina", "109"),
    "frosinone": ("Frosinone", "4057"),
    "genoa": ("Genoa", "3263"),
    "internazionale": ("Internazionale", "110"),
    "juventus": ("Juventus", "111"),
    "lazio": ("Lazio", "112"),
    "lecce": ("Lecce", "113"),
    "monza": ("Monza", "4007"),
    "napoli": ("Napoli", "114"),
    "parma": ("Parma", "115"),
    "sassuolo": ("Sassuolo", "3997"),
    "torino": ("Torino", "239"),
    "udinese": ("Udinese", "118"),
    "venezia": ("Venezia", "17530"),
    # Ligue 1 (fra.1)
    "aj auxerre": ("AJ Auxerre", "172"),
    "as monaco": ("AS Monaco", "174"),
    "angers": ("Angers", "7868"),
    "brest": ("Brest", "6997"),
    "le havre ac": ("Le Havre AC", "3236"),
    "le mans": ("Le Mans", "2697"),
    "lens": ("Lens", "175"),
    "lille": ("Lille", "166"),
    "lorient": ("Lorient", "273"),
    "lyon": ("Lyon", "167"),
    "marseille": ("Marseille", "176"),
    "nice": ("Nice", "2502"),
    "paris fc": ("Paris FC", "6851"),
    "paris saint germain": ("Paris Saint-Germain", "160"),
    "stade rennais": ("Stade Rennais", "169"),
    "strasbourg": ("Strasbourg", "180"),
    "toulouse": ("Toulouse", "179"),
    "troyes": ("Troyes", "170"),
    # FIFA men's world ranking top 50 (20 July 2026).
    # National teams use stable internal IDs because ESPN's IDs vary between
    # international competitions; bot.py matches these against event names.
    "spain": ("Spain", "international:spain"),
    "argentina": ("Argentina", "international:argentina"),
    "france": ("France", "international:france"),
    "england": ("England", "international:england"),
    "brazil": ("Brazil", "international:brazil"),
    "morocco": ("Morocco", "international:morocco"),
    "portugal": ("Portugal", "international:portugal"),
    "belgium": ("Belgium", "international:belgium"),
    "netherlands": ("Netherlands", "international:netherlands"),
    "mexico": ("Mexico", "international:mexico"),
    "colombia": ("Colombia", "international:colombia"),
    "germany": ("Germany", "international:germany"),
    "croatia": ("Croatia", "international:croatia"),
    "switzerland": ("Switzerland", "international:switzerland"),
    "italy": ("Italy", "international:italy"),
    "united states": ("United States", "international:united-states"),
    "japan": ("Japan", "international:japan"),
    "senegal": ("Senegal", "international:senegal"),
    "norway": ("Norway", "international:norway"),
    "uruguay": ("Uruguay", "international:uruguay"),
    "denmark": ("Denmark", "international:denmark"),
    "iran": ("Iran", "international:iran"),
    "austria": ("Austria", "international:austria"),
    "egypt": ("Egypt", "international:egypt"),
    "ecuador": ("Ecuador", "international:ecuador"),
    "nigeria": ("Nigeria", "international:nigeria"),
    "turkey": ("Turkey", "international:turkey"),
    "australia": ("Australia", "international:australia"),
    "algeria": ("Algeria", "international:algeria"),
    "canada": ("Canada", "international:canada"),
    "ivory coast": ("Ivory Coast", "international:ivory-coast"),
    "south korea": ("South Korea", "international:south-korea"),
    "ukraine": ("Ukraine", "international:ukraine"),
    "paraguay": ("Paraguay", "international:paraguay"),
    "russia": ("Russia", "international:russia"),
    "poland": ("Poland", "international:poland"),
    "sweden": ("Sweden", "international:sweden"),
    "wales": ("Wales", "international:wales"),
    "hungary": ("Hungary", "international:hungary"),
    "serbia": ("Serbia", "international:serbia"),
    "dr congo": ("DR Congo", "international:dr-congo"),
    "scotland": ("Scotland", "international:scotland"),
    "cameroon": ("Cameroon", "international:cameroon"),
    "panama": ("Panama", "international:panama"),
    "slovakia": ("Slovakia", "international:slovakia"),
    "greece": ("Greece", "international:greece"),
    "venezuela": ("Venezuela", "international:venezuela"),
    "czech republic": ("Czech Republic", "international:czech-republic"),
    "chile": ("Chile", "international:chile"),
    "peru": ("Peru", "international:peru"),
}


ESPN_LEAGUE_TEAMS = (
    # EFL Championship (eng.2)
    ("Swansea City", "318"), ("West Ham United", "371"), ("Middlesbrough", "369"),
    ("Wolverhampton Wanderers", "380"), ("West Bromwich Albion", "383"),
    ("Queens Park Rangers", "334"), ("Stoke City", "336"), ("Bristol City", "333"),
    ("Charlton Athletic", "372"), ("Birmingham City", "392"), ("Millwall", "391"),
    ("Lincoln City", "314"), ("Southampton", "376"), ("Wrexham", "352"),
    ("Norwich City", "381"), ("Blackburn Rovers", "365"), ("Sheffield United", "398"),
    ("Portsmouth", "385"), ("Watford", "395"), ("Cardiff City", "347"),
    ("Bolton Wanderers", "358"), ("Derby County", "374"), ("Preston North End", "394"),
    ("Burnley", "379"),
    # LALIGA 2 (esp.2)
    ("Castellón", "4438"), ("Eibar", "3752"), ("Mallorca", "84"), ("Girona", "9812"),
    ("Las Palmas", "98"), ("Sporting Gijón", "3788"), ("Tenerife", "245"),
    ("Almería", "6832"), ("Real Oviedo", "92"), ("Burgos", "12597"),
    ("Real Sociedad II", "20983"), ("Granada", "3747"), ("CD Sabadell", "11487"),
    ("Leganés", "17534"), ("RC Celta Fortuna", "131858"), ("Córdoba", "8447"),
    ("Eldense", "7320"), ("Real Valladolid", "95"), ("Cádiz", "3842"),
    ("FC Andorra", "20179"), ("Albacete", "2737"), ("Ceuta", "5404"),
    # 2. Bundesliga (ger.2)
    ("Hertha Berlin", "129"), ("1. FC Nürnberg", "269"), ("1. FC Heidenheim 1846", "6418"),
    ("VfL Wolfsburg", "138"), ("Kaiserslautern", "130"), ("1. FC Magdeburg", "10382"),
    ("Energie Cottbus", "123"), ("St. Pauli", "270"), ("VfL Bochum", "121"),
    ("Hannover 96", "2428"), ("VfL Osnabruck", "7013"), ("SpVgg Greuther Fürth", "3070"),
    ("Karlsruher SC", "4471"), ("TSV Eintracht Braunschweig", "3067"),
    ("Arminia Bielefeld", "2506"), ("Holstein Kiel", "7884"), ("Dynamo Dresden", "7017"),
    ("SV Darmstadt 98", "3812"),
    # Serie B (ita.2)
    ("Palermo", "2923"), ("Mantova", "3991"), ("Ascoli", "3346"), ("Sudtirol", "11139"),
    ("Modena", "2573"), ("Cesena", "3337"), ("US Avellino", "4055"),
    ("Benevento", "4059"), ("Padova", "3952"), ("Pisa", "3956"), ("Empoli", "2574"),
    ("Arezzo", "3345"), ("Vicenza", "120"), ("Virtus Entella", "11137"),
    ("Cremonese", "4050"), ("Hellas Verona", "119"), ("Sampdoria", "2734"),
    ("Juve Stabia", "3975"), ("Catanzaro", "3257"), ("Carrarese", "3988"),
    # Ligue 2 (fra.2)
    ("Nantes", "165"), ("Guingamp", "171"), ("Metz", "177"), ("Saint-Étienne", "178"),
    ("Sochaux", "272"), ("Montpellier", "274"), ("Dijon FCO", "3170"),
    ("Clermont Foot", "3171"), ("Stade de Reims", "3243"), ("Stade Laval", "3266"),
    ("AS Nancy Lorraine", "3267"), ("Grenoble", "6994"), ("Rodez Aveyron", "7719"),
    ("Dunkerque", "7732"), ("Boulogne", "7869"), ("Pau", "10678"),
    ("Red Star FC 93", "11884"), ("Annecy", "18066"),
    # Primeira Liga (por.1)
    ("FC Porto", "437"), ("Benfica", "1929"), ("Sporting CP", "2250"),
    ("Santa Clara", "12215"), ("Arouca", "15784"), ("Estrela", "21610"),
    ("Braga", "2994"), ("Académico de Viseu", "21607"), ("Maritimo", "552"),
    ("Gil Vicente", "3699"), ("Alverca", "21613"), ("FC Famalicao", "12698"),
    ("Moreirense", "3696"), ("Vitória de Guimaraes", "5309"), ("C.D. Nacional", "3472"),
    ("Rio Ave", "3822"), ("Estoril", "12216"), ("Casa Pia", "21581"),
    # Eredivisie (ned.1)
    ("Feyenoord Rotterdam", "142"), ("PSV Eindhoven", "148"), ("AZ Alkmaar", "140"),
    ("Ajax Amsterdam", "139"), ("FC Twente", "152"), ("Fortuna Sittard", "143"),
    ("Excelsior", "2566"), ("FC Groningen", "145"), ("Go Ahead Eagles", "3706"),
    ("Heerenveen", "146"), ("NEC Nijmegen", "147"), ("Telstar", "3735"),
    ("Sparta Rotterdam", "151"), ("SC Cambuur", "3736"), ("FC Utrecht", "153"),
    ("PEC Zwolle", "2565"), ("ADO Den Haag", "2726"), ("Willem II", "156"),
    # Süper Lig (tur.1)
    ("Galatasaray", "432"), ("Besiktas", "1895"), ("Kocaelispor", "995"),
    ("Alanyaspor", "9078"), ("Trabzonspor", "997"), ("Amed SFK", "132335"),
    ("Kasimpasa", "6870"), ("Caykur Rizespor", "7656"), ("Gaziantep FK", "20070"),
    ("Fenerbahce", "436"), ("Çorum FK", "132334"), ("Istanbul Basaksehir", "7914"),
    ("Genclerbirligi", "996"), ("Konyaspor", "7648"), ("Samsunspor", "11429"),
    ("Erzurum BB", "19267"), ("Eyupspor", "20729"), ("Goztepe", "789"),
    # Major League Soccer (usa.1)
    ("Chicago Fire FC", "182"), ("Columbus Crew", "183"), ("Colorado Rapids", "184"),
    ("FC Dallas", "185"), ("Sporting Kansas City", "186"), ("LA Galaxy", "187"),
    ("New England Revolution", "189"), ("Red Bull New York", "190"),
    ("San Jose Earthquakes", "191"), ("D.C. United", "193"), ("Real Salt Lake", "4771"),
    ("Houston Dynamo FC", "6077"), ("Toronto FC", "7318"), ("CF Montréal", "9720"),
    ("Portland Timbers", "9723"), ("Seattle Sounders FC", "9726"),
    ("Vancouver Whitecaps", "9727"), ("Philadelphia Union", "10739"),
    ("Orlando City SC", "12011"), ("Minnesota United FC", "17362"),
    ("New York City FC", "17606"), ("FC Cincinnati", "18267"),
    ("Atlanta United FC", "18418"), ("LAFC", "18966"), ("Nashville SC", "18986"),
    ("Inter Miami CF", "20232"), ("Austin FC", "20906"), ("Charlotte FC", "21300"),
    ("St. Louis CITY SC", "21812"), ("San Diego FC", "22529"),
    # Saudi Pro League (ksa.1)
    ("Al Shabab", "793"), ("Al Nassr", "817"), ("Al Hilal", "929"),
    ("Al Ittihad", "2276"), ("Al Ahli", "8346"), ("Al Ettifaq", "8363"),
    ("Al Fateh", "13033"), ("Al Taawoun", "18459"), ("Al Faisaly", "21446"),
    ("Al Fayha", "21827"), ("Al Khaleej", "21829"), ("Abha", "21833"),
    ("Al Hazem", "21964"), ("Al Riyadh", "21965"), ("Al Qadsiah", "22022"),
    ("Al Kholood", "22028"), ("Neom SC", "130899"), ("Al Diriyah", "131746"),
)

for _team_name, _team_id in ESPN_LEAGUE_TEAMS:
    _team_key = " ".join(_team_name.casefold().replace("-", " ").split())
    TEAMS[_team_key] = (_team_name, _team_id)

ALIASES = {
    "barca": "barcelona",
    "bournemouth": "afc bournemouth",
    "brighton": "brighton & hove albion",
    "leeds": "leeds united",
    "man city": "manchester city",
    "man united": "manchester united",
    "man utd": "manchester united",
    "newcastle": "newcastle united",
    "tottenham": "tottenham hotspur",
    "real madrid cf": "real madrid",
    "athletico madrid": "atletico madrid",
    "gladbach": "borussia monchengladbach",
    "fc bayern munich": "bayern munich",
    "inter milan": "internazionale",
    "inter": "internazionale",
    "roma": "as roma",
    "psg": "paris saint germain",
    "paris saint-germain": "paris saint germain",
    "rennes": "stade rennais",
    "monaco": "as monaco",
    "hoffenheim": "tsg hoffenheim",
    "stuttgart": "vfb stuttgart",
    "auxerre": "aj auxerre",
    "lens": "rc lens",
    "schalke": "schalke 04",
    "freiburg": "sc freiburg",
    "hamburg": "hamburg sv",
    "cologne": "fc cologne",
    "augsburg": "fc augsburg",
    "spurs": "tottenham hotspur",
    "fc barcelona": "barcelona",
    "man c": "manchester city",
    "man u": "manchester united",
    "frankfurt": "eintracht frankfurt",
    "betis": "real betis",
    "sociedad": "real sociedad",
    "villarreal cf": "villarreal",
    "rmad": "real madrid",
    "atletico": "atletico madrid",
    "union berlin": "1 fc union berlin",
    "celta": "celta vigo",
    "nottingham": "nottingham forest",
    "deportivo la coruna": "deportivo",
    "deportivo coruna": "deportivo",
    "deportivo alaves": "alaves",
    "haramball fc": "atletico madrid",
    "usa": "united states",
    "usmnt": "united states",
    "espana": "spain",
    "españa": "spain",
    "la roja": "spain",
    "spain national team": "spain",
    "seleccion espanola": "spain",
    "selección española": "spain",
    "the netherlands": "netherlands",
    "holland": "netherlands",
    "cote d ivoire": "ivory coast",
    "cote d'ivoire": "ivory coast",
    "côte d'ivoire": "ivory coast",
    "ivory coast national team": "ivory coast",
    "korea republic": "south korea",
    "south korea national team": "south korea",
    "turkiye": "turkey",
    "türkiye": "turkey",
    "congo dr": "dr congo",
    "democratic republic of congo": "dr congo",
    "czechia": "czech republic",
}


COMPETITIONS = {
    "premier league": ("Premier League", "eng.1"),
    "la liga": ("La Liga", "esp.1"),
    "bundesliga": ("Bundesliga", "ger.1"),
    "serie a": ("Serie A", "ita.1"),
    "ligue 1": ("Ligue 1", "fra.1"),
    "uefa champions league": ("UEFA Champions League", "uefa.champions"),
    "uefa europa league": ("UEFA Europa League", "uefa.europa"),
    "uefa conference league": ("UEFA Conference League", "uefa.europa.conf"),
    "fa cup": ("FA Cup", "eng.fa"),
    "copa del rey": ("Copa del Rey", "esp.copa_del_rey"),
    "dfb pokal": ("DFB-Pokal", "ger.dfb_pokal"),
    "coppa italia": ("Coppa Italia", "ita.coppa_italia"),
    "coupe de france": ("Coupe de France", "fra.coupe_de_france"),
    "efl championship": ("EFL Championship", "eng.2"),
    "la liga 2": ("La Liga 2", "esp.2"),
    "2 bundesliga": ("2. Bundesliga", "ger.2"),
    "serie b": ("Serie B", "ita.2"),
    "ligue 2": ("Ligue 2", "fra.2"),
    "primeira liga": ("Primeira Liga", "por.1"),
    "eredivisie": ("Eredivisie", "ned.1"),
    "super lig": ("Süper Lig", "tur.1"),
    "major league soccer": ("Major League Soccer", "usa.1"),
    "saudi pro league": ("Saudi Pro League", "ksa.1"),
}

COMPETITION_ALIASES = {
    "epl": "premier league",
    "english premier league": "premier league",
    "english league": "premier league",
    "spanish league": "la liga",
    "la liga ea sports": "la liga",
    "german league": "bundesliga",
    "italian league": "serie a",
    "french league": "ligue 1",
    "fa cup": "fa cup",
    "english fa cup": "fa cup",
    "copa del rey": "copa del rey",
    "spanish cup": "copa del rey",
    "dfb pokal": "dfb pokal",
    "german cup": "dfb pokal",
    "coppa italia": "coppa italia",
    "italian cup": "coppa italia",
    "coupe de france": "coupe de france",
    "french cup": "coupe de france",
    "championship": "efl championship",
    "efl": "efl championship",
    "english championship": "efl championship",
    "segunda division": "la liga 2",
    "segunda división": "la liga 2",
    "spanish second division": "la liga 2",
    "2. bundesliga": "2 bundesliga",
    "german second division": "2 bundesliga",
    "italian second division": "serie b",
    "french second division": "ligue 2",
    "portuguese league": "primeira liga",
    "portuguese primeira liga": "primeira liga",
    "dutch league": "eredivisie",
    "turkish league": "super lig",
    "süper lig": "super lig",
    "mls": "major league soccer",
    "saudi league": "saudi pro league",
    "saudi arabia pro league": "saudi pro league",
    "ucl": "uefa champions league",
    "champions league": "uefa champions league",
    "uefa champions": "uefa champions league",
    "uel": "uefa europa league",
    "uecl": "uefa conference league",
}


def find_team(name: str):
    """Return the canonical display name and ESPN ID for a team name."""
    key = " ".join(name.casefold().replace("-", " ").split())
    key = ALIASES.get(key, key)
    return TEAMS.get(key)


def find_competition(name: str):
    """Return the canonical display name and ESPN code for a supported competition."""
    key = " ".join(name.casefold().replace("-", " ").split())
    key = COMPETITION_ALIASES.get(key, key)
    return COMPETITIONS.get(key)
