"""ESPN IDs for the current clubs in Europe's five major leagues.

The canonical entries are taken from ESPN's league team feeds for the 2026
season. Keys are normalized lower-case names; aliases are included where a
club is commonly known by a different name.
"""

TEAMS = {
    # English Premier League (eng.1)
    "afc bournemouth": ("AFC Bournemouth", "349"),
    "arsenal": ("Arsenal", "359"),
    "aston villa": ("Aston Villa", "362"),
    "brentford": ("Brentford", "337"),
    "brighton & hove albion": ("Brighton & Hove Albion", "331"),
    "chelsea": ("Chelsea", "363"),
    "coventry city": ("Coventry City", "388"),
    "crystal palace": ("Crystal Palace", "384"),
    "everton": ("Everton", "368"),
    "fulham": ("Fulham", "370"),
    "hull city": ("Hull City", "306"),
    "ipswich town": ("Ipswich Town", "373"),
    "leeds united": ("Leeds United", "357"),
    "liverpool": ("Liverpool", "364"),
    "manchester city": ("Manchester City", "382"),
    "manchester united": ("Manchester United", "360"),
    "newcastle united": ("Newcastle United", "361"),
    "nottingham forest": ("Nottingham Forest", "393"),
    "sunderland": ("Sunderland", "366"),
    "tottenham hotspur": ("Tottenham Hotspur", "367"),
    # La Liga (esp.1)
    "alaves": ("Alavés", "96"),
    "athletic club": ("Athletic Club", "93"),
    "atletico madrid": ("Atlético Madrid", "1068"),
    "barcelona": ("Barcelona", "83"),
    "celta vigo": ("Celta Vigo", "85"),
    "deportivo": ("Deportivo", "90"),
    "elche": ("Elche", "3751"),
    "espanyol": ("Espanyol", "88"),
    "getafe": ("Getafe", "2922"),
    "levante": ("Levante", "1538"),
    "malaga": ("Málaga", "99"),
    "osasuna": ("Osasuna", "97"),
    "racing santander": ("Racing Santander", "87"),
    "rayo vallecano": ("Rayo Vallecano", "101"),
    "real betis": ("Real Betis", "244"),
    "real madrid": ("Real Madrid", "86"),
    "real sociedad": ("Real Sociedad", "89"),
    "sevilla": ("Sevilla", "243"),
    "valencia": ("Valencia", "94"),
    "villarreal": ("Villarreal", "102"),
    # Bundesliga (ger.1)
    "1 fc union berlin": ("1. FC Union Berlin", "598"),
    "bayer leverkusen": ("Bayer Leverkusen", "131"),
    "bayern munich": ("Bayern Munich", "132"),
    "borussia dortmund": ("Borussia Dortmund", "124"),
    "borussia monchengladbach": ("Borussia Mönchengladbach", "268"),
    "eintracht frankfurt": ("Eintracht Frankfurt", "125"),
    "fc augsburg": ("FC Augsburg", "3841"),
    "fc cologne": ("FC Cologne", "122"),
    "hamburg sv": ("Hamburg SV", "127"),
    "mainz": ("Mainz", "2950"),
    "rb leipzig": ("RB Leipzig", "11420"),
    "sc freiburg": ("SC Freiburg", "126"),
    "sc paderborn 07": ("SC Paderborn 07", "3307"),
    "sv elversberg": ("SV Elversberg", "10388"),
    "schalke 04": ("Schalke 04", "133"),
    "tsg hoffenheim": ("TSG Hoffenheim", "7911"),
    "vfb stuttgart": ("VfB Stuttgart", "134"),
    "werder bremen": ("Werder Bremen", "137"),
    # Serie A (ita.1)
    "ac milan": ("AC Milan", "103"),
    "as roma": ("AS Roma", "104"),
    "atalanta": ("Atalanta", "105"),
    "bologna": ("Bologna", "107"),
    "cagliari": ("Cagliari", "2925"),
    "como": ("Como", "2572"),
    "fiorentina": ("Fiorentina", "109"),
    "frosinone": ("Frosinone", "4057"),
    "genoa": ("Genoa", "3263"),
    "internazionale": ("Internazionale", "110"),
    "juventus": ("Juventus", "111"),
    "lazio": ("Lazio", "112"),
    "lecce": ("Lecce", "113"),
    "monza": ("Monza", "4007"),
    "napoli": ("Napoli", "114"),
    "parma": ("Parma", "115"),
    "sassuolo": ("Sassuolo", "3997"),
    "torino": ("Torino", "239"),
    "udinese": ("Udinese", "118"),
    "venezia": ("Venezia", "17530"),
    # Ligue 1 (fra.1)
    "aj auxerre": ("AJ Auxerre", "172"),
    "as monaco": ("AS Monaco", "174"),
    "angers": ("Angers", "7868"),
    "brest": ("Brest", "6997"),
    "le havre ac": ("Le Havre AC", "3236"),
    "le mans": ("Le Mans", "2697"),
    "lens": ("Lens", "175"),
    "lille": ("Lille", "166"),
    "lorient": ("Lorient", "273"),
    "lyon": ("Lyon", "167"),
    "marseille": ("Marseille", "176"),
    "nice": ("Nice", "2502"),
    "paris fc": ("Paris FC", "6851"),
    "paris saint germain": ("Paris Saint-Germain", "160"),
    "stade rennais": ("Stade Rennais", "169"),
    "strasbourg": ("Strasbourg", "180"),
    "toulouse": ("Toulouse", "179"),
    "troyes": ("Troyes", "170"),
}

ALIASES = {
    "barca": "barcelona",
    "bournemouth": "afc bournemouth",
    "brighton": "brighton & hove albion",
    "leeds": "leeds united",
    "man city": "manchester city",
    "man united": "manchester united",
    "man utd": "manchester united",
    "newcastle": "newcastle united",
    "tottenham": "tottenham hotspur",
    "real madrid cf": "real madrid",
    "athletico madrid": "atletico madrid",
    "gladbach": "borussia monchengladbach",
    "fc bayern munich": "bayern munich",
    "inter milan": "internazionale",
    "inter": "internazionale",
    "roma": "as roma",
    "psg": "paris saint germain",
    "paris saint-germain": "paris saint germain",
    "rennes": "stade rennais",
    "monaco": "as monaco",
    "hoffenheim": "tsg hoffenheim",
    "stuttgart": "vfb stuttgart",
    "auxerre": "aj auxerre",
    "lens": "rc lens",
    "schalke": "schalke 04",
    "freiburg": "sc freiburg",
    "hamburg": "hamburg sv",
    "cologne": "fc cologne",
    "augsburg": "fc augsburg",
    "spurs": "tottenham hotspur",
    "fc barcelona": "barcelona",
    "man c": "manchester city",
    "man u": "manchester united",
    "frankfurt": "eintracht frankfurt",
    "betis": "real betis",
    "sociedad": "real sociedad",
    "villarreal cf": "villarreal",
    "rmad": "real madrid",
    "atletico": "atletico madrid",
    "union berlin": "1 fc union berlin",
    "celta": "celta vigo",
    "nottingham": "nottingham forest",
    "deportivo la coruna": "deportivo",
    "deportivo coruna": "deportivo",
    "deportivo alaves": "alaves",
    "haramball fc": "atletico madrid"
}


COMPETITIONS = {
    "premier league": ("Premier League", "eng.1"),
    "la liga": ("La Liga", "esp.1"),
    "bundesliga": ("Bundesliga", "ger.1"),
    "serie a": ("Serie A", "ita.1"),
    "ligue 1": ("Ligue 1", "fra.1"),
    "uefa champions league": ("UEFA Champions League", "uefa.champions"),
    "fa cup": ("FA Cup", "eng.fa"),
    "copa del rey": ("Copa del Rey", "esp.copa_del_rey"),
    "dfb pokal": ("DFB-Pokal", "ger.dfb_pokal"),
    "coppa italia": ("Coppa Italia", "ita.coppa_italia"),
    "coupe de france": ("Coupe de France", "fra.coupe_de_france"),
}

COMPETITION_ALIASES = {
    "epl": "premier league",
    "english premier league": "premier league",
    "english league": "premier league",
    "spanish league": "la liga",
    "la liga ea sports": "la liga",
    "german league": "bundesliga",
    "italian league": "serie a",
    "french league": "ligue 1",
    "fa cup": "fa cup",
    "english fa cup": "fa cup",
    "copa del rey": "copa del rey",
    "spanish cup": "copa del rey",
    "dfb pokal": "dfb pokal",
    "german cup": "dfb pokal",
    "coppa italia": "coppa italia",
    "italian cup": "coppa italia",
    "coupe de france": "coupe de france",
    "french cup": "coupe de france",
    "ucl": "uefa champions league",
    "champions league": "uefa champions league",
    "uefa champions": "uefa champions league",
}


def find_team(name: str):
    """Return the canonical display name and ESPN ID for a team name."""
    key = " ".join(name.casefold().replace("-", " ").split())
    key = ALIASES.get(key, key)
    return TEAMS.get(key)


def find_competition(name: str):
    """Return the canonical display name and ESPN code for a supported competition."""
    key = " ".join(name.casefold().replace("-", " ").split())
    key = COMPETITION_ALIASES.get(key, key)
    return COMPETITIONS.get(key)
